// Copyright 2025 The FluidMarkdown Authors. All rights reserved.
// Use of this source code is governed by a Apache 2.0 license that can be
// found in the LICENSE file.

#import "AMLayoutManager.h"
#import "AMDrawable.h"
#import "AMViewAttachment.h"
#import "AMLayoutManager+Quote.h"
#import "AMIconLinkAttachment.h"
#import "AMImageTextAttachment.h"

@implementation AMLayoutManager

// 子类化说明：
// AMLayoutManager 继承系统的 NSLayoutManager，通过重写绘制相关方法，实现 Markdown 渲染所需的“额外绘制能力”和“交互区域收集”。
// 具体发挥的作用包括：
// 1) 背景绘制扩展：支持 AMDrawable/AMBackgroundDrawableAttributeName，在行片段维度按内联/块级分别绘制（如引用背景、代码块背景）。
// 2) 下划线绘制扩展：支持 AMUnderlineDrawable，在系统下划线之后按自定义样式补充绘制（用于任务列表、链接特殊样式等）。
// 3) 布局阶段收集交互区域：在 drawGlyphsForGlyphRange 中计算附件（图片/图标链接）与超链接的真实显示矩形，通知外部 delegate 用于命中测试与交互。
// 4) 视图型附件定位：当属性值符合 AMViewAttachment 协议时，将其 UIView 准确定位到对应字形范围的矩形并显示。
/*
 这些方法是用于绘制的基础方法。你可以重写它们来执行额外的绘制操作，或者完全替换文字绘制的逻辑，但不能用于更改布局。
 如果你需要手动调用它们，必须确保目标视图或图像的绘制焦点（focus）已经被锁定。
     •    -drawBackgroundForGlyphRange:atPoint:
 负责绘制文字的背景颜色、选中区域、标记范围（如输入法高亮）等内容，以及块级装饰（例如表格的背景和边框）。
     •    -drawGlyphsForGlyphRange:atPoint:
 负责绘制实际的字形（glyph），包括附件（attachments），以及下划线、删除线等装饰。

 需要注意的是，在任一情况下，传入的所有字形（glyph）都必须属于同一个文本容器（text container）。
 */
- (void)drawBackgroundForGlyphRange:(NSRange)glyphsToShow
                            atPoint:(CGPoint)origin
{
    [super drawBackgroundForGlyphRange:glyphsToShow atPoint:origin];
    
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, origin.x, origin.y);
    
    /*
     // Returns the range of characters that generated the glyphs in the given glyphRange.  If actualGlyphRange is not NULL, it will return by reference the full range of glyphs generated by the character range returned.  This range may be identical or slightly larger than the requested glyph range.  For example, if the text storage contains the character (o-umlaut) and the glyph store contains the two atomic glyphs "o" and (umlaut), and if the glyph range given encloses only the first or second glyph, then actualGlyphRange will be set to enclose both glyphs.  If the length of glyphRange is zero, the resulting character range will be a zero-length range just after the character(s) corresponding to the preceding glyph, and actualGlyphRange will also be zero-length.  If non-contiguous layout is not enabled, this will force the generation of glyphs for all characters up to and including the end of the returned range.
     返回给定 glyphRange（字形范围）所对应的字符范围。
     如果 actualGlyphRange 不为 NULL，则会通过引用返回一个“完整的”字形范围，该范围由返回的字符范围所生成。这个范围可能与请求的 glyphRange 完全相同，也可能略大一些。

     例如：
     如果文本存储中有一个带分音符的字符 “ö” (o-umlaut)，而字形存储中包含两个独立的原子字形 —— “o” 和 “¨”（分音符），
     当你传入的 glyphRange 只包含其中一个字形（比如只包含 “o” 或 “¨”）时，返回的 actualGlyphRange 将会被扩展，包含这两个字形。

     如果传入的 glyphRange 长度为 0，则返回的字符范围也是一个 长度为 0 的范围，位置在前一个字形对应字符的后面；此时 actualGlyphRange 也为 0 长度。

     另外，如果未启用“非连续布局（non-contiguous layout）”，则调用此方法会强制生成从起始位置到返回范围末尾之间的所有字符对应的字形。
     */
    NSRange charactorRange = [self characterRangeForGlyphRange:glyphsToShow
                                              actualGlyphRange:NULL];
    
    AMQuoteLayoutContext *quoteContext = [AMQuoteLayoutContext new];
    // AMBackgroundDrawableAttributeName 这个属性, 会在 代码块被识别的时候添加.
    [self.textStorage enumerateAttribute:AMBackgroundDrawableAttributeName
                                 inRange:charactorRange
                                 options:0
                              usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
        // 背景绘制扩展：当属性值实现 AMDrawable 协议时，由子类负责调用其绘制逻辑。
        if ([value conformsToProtocol:@protocol(AMDrawable)]) {
            id<AMDrawable> drawable = (id<AMDrawable>)value;
            BOOL isInline = YES;
            if ([drawable respondsToSelector:@selector(isInline)]) {
                isInline = [drawable isInline];
            }
            
            // 引用等特殊块级背景，由分类 AMLayoutManager+Quote 进行统一处理（可能跨多行片段）。
            if ([self handleQuoteDraw:context
                         quoteContext:quoteContext
                             drawable:drawable
                                range:range]) {
                return;
            }
            
            if (isInline) {
                // 内联背景：按行片段逐段绘制，确保跨行时边缘裁剪正确。
                [self enumerateLineFragmentsForGlyphRange:range
                                               usingBlock:^(CGRect rect, CGRect usedRect, NSTextContainer * _Nonnull textContainer, NSRange glyphRange, BOOL * _Nonnull stop) {
                    NSRange intersectRange = NSIntersectionRange(range, glyphRange);
                    CGRect bounds = [self boundingRectForGlyphRange:intersectRange inTextContainer:textContainer];
                    UIRectEdge edges = UIRectEdgeNone;
                    if (NSEqualRanges(intersectRange, range)) {
                        edges = UIRectEdgeNone;
                    } else if (intersectRange.location == range.location && intersectRange.length < range.location) {
                        edges = UIRectEdgeRight;
                    } else if (intersectRange.location > range.location && NSMaxRange(intersectRange) < NSMaxRange(range)) {
                        edges = UIRectEdgeRight | UIRectEdgeLeft;
                    } else if (intersectRange.location > range.location && NSMaxRange(intersectRange) == NSMaxRange(range)) {
                        edges = UIRectEdgeLeft;
                    }
                    CGContextSaveGState(context);
                    [drawable drawInRect:bounds clipEdges:edges];
                    CGContextRestoreGState(context);
                }];
            } else {
                // 块级背景：先合并所有相关行片段的外接矩形，再整体绘制一次，避免断裂。
                __block CGRect bounds = CGRectNull;
                [self enumerateLineFragmentsForGlyphRange:range
                                               usingBlock:^(CGRect rect, CGRect usedRect, NSTextContainer * _Nonnull textContainer, NSRange glyphRange, BOOL * _Nonnull stop) {
                    if (CGRectIsNull(bounds)) {
                        bounds = UIEdgeInsetsInsetRect(rect, UIEdgeInsetsMake(0, textContainer.lineFragmentPadding, 0, textContainer.lineFragmentPadding));
                    } else {
                        bounds = CGRectUnion(bounds, UIEdgeInsetsInsetRect(rect, UIEdgeInsetsMake(0, textContainer.lineFragmentPadding, 0, textContainer.lineFragmentPadding)));
                    }
                }];
                CGContextSaveGState(context);
                [drawable drawInRect:bounds clipEdges:UIRectEdgeNone];
                CGContextRestoreGState(context);
            }
        }
    }];
    CGContextRestoreGState(context);
}

- (void)drawStrikethroughForGlyphRange:(NSRange)glyphRange
                     strikethroughType:(NSUnderlineStyle)strikethroughVal
                        baselineOffset:(CGFloat)baselineOffset
                      lineFragmentRect:(CGRect)lineRect
                lineFragmentGlyphRange:(NSRange)lineGlyphRange
                       containerOrigin:(CGPoint)containerOrigin
{
    [super drawStrikethroughForGlyphRange:glyphRange
                        strikethroughType:strikethroughVal
                           baselineOffset:baselineOffset
                         lineFragmentRect:lineRect
                   lineFragmentGlyphRange:lineGlyphRange
                          containerOrigin:containerOrigin];
}

- (void)drawUnderlineForGlyphRange:(NSRange)glyphRange
                     underlineType:(NSUnderlineStyle)underlineVal
                    baselineOffset:(CGFloat)baselineOffset
                  lineFragmentRect:(CGRect)lineRect
            lineFragmentGlyphRange:(NSRange)lineGlyphRange
                       containerOrigin:(CGPoint)containerOrigin
{
    [super drawUnderlineForGlyphRange:glyphRange
                        underlineType:underlineVal
                       baselineOffset:baselineOffset
                     lineFragmentRect:lineRect
               lineFragmentGlyphRange:lineGlyphRange
                      containerOrigin:containerOrigin];
    
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextSaveGState(context);
    
    NSRange charactorRange = [self characterRangeForGlyphRange:glyphRange
                                              actualGlyphRange:NULL];
    
    [self.textStorage enumerateAttribute:AMUnderlineDrawableAttributeName
                                 inRange:charactorRange
                                 options:0
                              usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
        // 下划线绘制扩展：当属性值实现 AMUnderlineDrawable 协议时，使用其自定义绘制逻辑增强系统下划线。
        if ([value conformsToProtocol:@protocol(AMUnderlineDrawable)]) {
            id<AMUnderlineDrawable> drawable = (id<AMUnderlineDrawable>)value;
            CGRect bounds = [self boundingRectForGlyphRange:range inTextContainer:[self textContainerForGlyphAtIndex:range.location effectiveRange:NULL]];
            CGPoint location = [self locationForGlyphAtIndex:range.location];
            CGContextSaveGState(context);
            [drawable drawInRect:CGRectMake(lineRect.origin.x + containerOrigin.x + location.x, lineRect.origin.y + containerOrigin.y, bounds.size.width, location.y)
                  underlineStyle:underlineVal
                  baselineOffset:baselineOffset];
            CGContextRestoreGState(context);
        }
    }];
    CGContextRestoreGState(context);
}

- (void)drawGlyphsForGlyphRange:(NSRange)glyphsToShow atPoint:(CGPoint)origin
{
    [super drawGlyphsForGlyphRange:glyphsToShow atPoint:origin];
    
    NSRange charactorRange = [self characterRangeForGlyphRange:glyphsToShow
                                              actualGlyphRange:NULL];
    if (!self.locArray) {
        self.locArray = [[NSMutableArray alloc] init];
    }
    if (!self.attachmentDic) {
        self.attachmentDic = [[NSMutableDictionary alloc] init];
    }
    
    
    [self.textStorage enumerateAttributesInRange:charactorRange options:0 usingBlock:^(NSDictionary<NSAttributedStringKey, id> *attrs, NSRange range, BOOL *stop) {
        // 交互区域收集：附件与链接的显示矩形，用于命中测试/高亮/点击处理。
        if ([attrs.allKeys containsObject:NSAttachmentAttributeName]) {
            NSObject* attrValue = [attrs objectForKey:NSAttachmentAttributeName];
            if ([attrValue isKindOfClass:[AMIconLinkAttachment class]] || [attrValue isKindOfClass:[AMImageTextAttachment class]]) {
                ;
                if ([self.attachmentDic objectForKey:[NSString stringWithFormat:@"%p",attrValue]]) {
                    return;
                }
                CGRect rect = [self boundingRectForGlyphRange:range
                                              inTextContainer:[self textContainerForGlyphAtIndex:range.location
                                                                                  effectiveRange:NULL]];
                rect.origin.x += origin.x;
                rect.origin.y += origin.y;
                [self.locArray addObject:[NSValue valueWithCGRect:rect]];
                [self.attachmentDic setObject:attrValue forKey:[NSString stringWithFormat:@"%p",attrValue]];
            } else if ([attrValue conformsToProtocol:@protocol(AMViewAttachment)]) {
                // 视图型附件：将 UIView 直接放置到对应字形区域，参与交互。
                id<AMViewAttachment> attach = (id<AMViewAttachment>)attrValue;
                
                CGRect rect = [self boundingRectForGlyphRange:range
                                              inTextContainer:[self textContainerForGlyphAtIndex:range.location
                                                                                  effectiveRange:NULL]];
                rect.origin.x += origin.x;
                rect.origin.y += origin.y;
                attach.view.frame = rect;
                attach.view.hidden = NO;
            }
        } else if ([attrs.allKeys containsObject:NSLinkAttributeName]) {
            if ([self.attachmentDic objectForKey:[NSString stringWithFormat:@"%p",[attrs objectForKey:NSLinkAttributeName]]]) {
                return;
            }
            CGRect rect = [self boundingRectForGlyphRange:range
                                          inTextContainer:[self textContainerForGlyphAtIndex:range.location
                                                                              effectiveRange:NULL]];
            rect.origin.x += origin.x;
            rect.origin.y += origin.y;
            [self.locArray addObject:[NSValue valueWithCGRect:rect]];
            [self.attachmentDic setObject:[attrs objectForKey:NSLinkAttributeName] forKey:[NSString stringWithFormat:@"%p",[attrs objectForKey:NSLinkAttributeName]]];
        }
    }];
    
    if (self.delegate) {
        // 将收集到的矩形通知外部，用于命中测试/交互绑定（如点击链接或图片）。
        [self.delegate notifyNodeLocation:self.locArray];
    }
}

@end
